### DISCUSSION TITLE
Unable to start postgres or mysql DB due to password error.

### DISCUSSION THREAD

**Discussion by jakob4800** [benjaminjonard/koillection#1075] [Q&A]
### **!!! DISCLAIMER I AM A NOOB AND THIS IS MY FIRST TIME USING DOCKER !!!**

I've installed Koillection using docker compose on windows, i'm able to create accounts, sign in and use the app locally on my localhost at port 80. I can also see the sign in screen on other devices if i go to the servers IP however I can't actually sign in on these other devices, it just won't let me and doesn't present any error.

My theory is that the postgres DB is not running and because of that it won't let me access anything from outside the localhost. I checked this because I noticed that the container running the postgres exits and presents with the below error. I also tried switching it to the mySQL DB but a similar error also presents and the container/image won't start.

```2024-02-26 02:25:14 Error: Database is uninitialized and superuser password is not specified.
2024-02-26 02:25:14        You must specify POSTGRES_PASSWORD to a non-empty value for the
2024-02-26 02:25:14        superuser. For example, "-e POSTGRES_PASSWORD=password" on "docker run".
```
I've changed the password variable in the .env file from "ChangeMe!" to another one, the issue still exists. I've also given the below a shot after a suggestion from a friend however none of these steps have worked. In the docker-compose.yml i've tried keeping it default as well as changing environment variable to the below.

```  # Database : choose one of the following
    db:
        image: postgres:16
        container_name: db
        restart: unless-stopped
        env_file:
            - .env
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER="Admin"
            - POSTGRES_PASSWORD="SecretPass1"
        volumes:
            - "./volumes/postgresql:/var/lib/postgresql/data"
```  
I've also tried these too

```
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER= Admin
            - POSTGRES_PASSWORD= SecretPass1
            ________________________________________
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=Admin
            - POSTGRES_PASSWORD=SecretPass1
```

Current docker-compose.yml
```
version: '3'

services:
    # Koillection
    koillection:
        image: koillection/koillection
        container_name: koillection
        restart: unless-stopped
        ports:
            - 80:80
        env_file:
            - .env
        depends_on:
            - db
        volumes:
            - ./volumes/koillection/uploads:/uploads

    # Database : choose one of the following
    db:
        image: postgres:16
        container_name: db
        restart: unless-stopped
        env_file:
            - .env
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        volumes:
            - "./volumes/postgresql:/var/lib/postgresql/data"

    #db:
    #    image: mysql:latest
    #    container_name: db       
    #    restart: unless-stopped 
    #    environment:
    #        - MYSQL_DATABASE=${DB_NAME}
    #        - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    #    volumes:
    #        - "./docker/volumes/mysql:/var/lib/mysql"
```

Current .env
```
########################################################################################################
#                                                WEB
#
# APP_DEBUG=1 displays detailed error message
#
# APP_SECRET is a random string used for security, you can use for example openssl rand -base64 21
# APP_SECRET is automatically generated when using Docker
#
# PHP_TZ, see possible values here https://www.w3schools.com/php/php_ref_timezones.asp
########################################################################################################

APP_DEBUG=0
APP_ENV=prod
#APP_SECRET=

HTTPS_ENABLED=1
UPLOAD_MAX_FILESIZE=20M
PHP_MEMORY_LIMIT=512M
PHP_TZ=Europe/Paris


########################################################################################################
#                                                API
#
#
# JWT_PASSPHRASE is a random string used for security, you can use for example openssl rand -base64 21
# JWT_PASSPHRASE is automatically generated when using Docker
########################################################################################################

CORS_ALLOW_ORIGIN='^https?://(localhost|127\.0\.0\.1)(:[0-9]+)?$'
JWT_SECRET_KEY=%kernel.project_dir%/config/jwt/private.pem
JWT_PUBLIC_KEY=%kernel.project_dir%/config/jwt/public.pem
#JWT_PASSPHRASE=

########################################################################################################
#                                                DATABASE
########################################################################################################

DB_DRIVER=pdo_pgsql
DB_NAME=koillection
DB_HOST=db
DB_PORT=5432
DB_USER=koillection
DB_PASSWORD=Secret1
DB_VERSION=16
```
I've got no clue what i'm doing wrong, even if i leave everything as default, copied directly from the instructions it still won't world. this is my first time using docker and would appreciate any assistance.
