### DISCUSSION TITLE
Running Koillection on QNAP NAS using Container Station

### DISCUSSION THREAD

**Discussion by oywino** [benjaminjonard/koillection#1279] [Show and tell]
Since Container Station doesn't support using external environment file, all environment variables has to be  included in the Docker Compose file. After countless hours of trial'n'error I finally made it run. Here's my Docker Compose file using MySQL:

```
version: '3.8'

services:
    koillection:
        image: koillection/koillection:latest
        container_name: koillection
        restart: unless-stopped
        ports:
            - 9200:80                                         #use any port number of your choice
        environment:
            APP_DEBUG: "0"
            APP_ENV: "prod"
            HTTPS_ENABLED: "0"
            UPLOAD_MAX_FILESIZE: "20M"
            PHP_MEMORY_LIMIT: "512M"
            PHP_TZ: "Europe/Oslo"                  #Replace with your timezone
            CORS_ALLOW_ORIGIN: '^https?://(localhost|127\.0\.0\.1)(:[0-9]+)?$'
            JWT_SECRET_KEY: "/var/www/koillection/config/jwt/private.pem"
            JWT_PUBLIC_KEY: "/var/www/koillection/config/jwt/public.pem"
            DB_DRIVER: "pdo_mysql"
            DB_NAME: "koillection"
            DB_HOST: "db"
            DB_PORT: "3306"
            DB_USER: "koillection_user"
            DB_PASSWORD: "XXXXXXX"           #Replace with a password of your choice
            DB_VERSION: "8"
        depends_on:
            - db
        volumes:
            - /share/Public/koillection/uploads:/uploads

    db:
        image: mysql:8.0
        container_name: db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: "koillection"
            MYSQL_ROOT_PASSWORD: ""
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_USER: "koillection_user"
            MYSQL_PASSWORD: "XXXXXXX"         #Same password as above
        volumes:
            - /share/Public/koillection/mysql:/var/lib/mysql
```

The first time these two containers are spun up, it will take time because all database elements has to be generated. This can lead to a series of error messages in the log because the Koillection App may try to access the MySQL database before it's finished with the initial setup. Pay attention to the log. If it stops without any more lines added, but you are still unable to launch the App, then manually stop the container, wait and then restart it again. You may have to do this a couple of times initially, but from then on it shouldn't be necessary once you've passed the opening screen.
