### DISCUSSION TITLE
I have local mysql non docker already running, I want to reuse it and not allowed

### DISCUSSION THREAD

**Discussion by edrimon** [benjaminjonard/koillection#857] [Q&A]
Hi, 

There is already a non docker local Mysql I want to reuse, just to add a new DB called koillection etc. 

However if I remove that db part from docker-compose, as I do not want a mysql DB docker to start, I get the message: 
ERROR: Service 'koillection' depends on service 'db' which is undefined.

I do not find also any config parameters related. So the question is, how can I run koillektion with an already existing DB? Or even to connect to an external mysql/postgress DB etc. not requiring to start a local docker instance just for koillection?

**Comment by benjaminjonard** [comment]
Hello, 

I don't have an easy way to test this, but you should be able to achieve this by removing the `depends_on` property and adding a `network_mode` property :


```
version: '3'

services:
    # Koillection
    koillection:
        image: koillection/koillection
        container_name: koillection
        restart: unless-stopped
        network_mode: host
        ports:
            - 80:80
        env_file:
            - .env
        volumes:
            - ./volumes/koillection/uploads:/uploads

```

Then in your .env file you should update DB_HOST with your database IP

Make sure your database is started before starting the Koillection container

**Reply by edrimon** [reply]
Tried that , after downloading the containers, it crashes with error:
ERROR: for koillection  "host" network_mode is incompatible with port_bindings

I guess I need some tuning in the docker compose level but I need to dig and I am not so familiar..

**Reply by benjaminjonard** [reply]
Yes, I guess you have to remove the `ports` property too

**Comment by edrimon** [comment]
I do not think the ports should be removed, as I want the docker to listen
to a port and this to be mapped to the O/S port in order to be called and
reachable by other services, from what I understand.

Anyway, I think I got it, I will reply hopefully soon that it was solved.

thanks

**Comment by edrimon** [comment]
I tried now to follow the alternative for installation,

1.  php bin/console bazinga:js-translation:dump assets/js --format=js
says:  There are no commands defined in the "bazinga:js-translation"
namespace.  Did you mean this?      app:translations

2. Configure a vhost (you can find an example for nginx in docs folder)  ->
(There is nowhere a "docs" folder)
3. Generate assets : cd assets/ && yarn install && yarn build && cd ..
-> 00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'
It seems there is no file or directory "install" inside assets folder but
other files.

Can you please advice?

**Reply by benjaminjonard** [reply]
I updated the wiki, it was a bit outdated. Very few people uses this installation method, I think it's really going the hard way

1. I updated the command, it is `php bin/console app:translations:dump` now
2. There is a nginx vhost in the docker folder you can use as an exemple (it's the vhost used by the docker container)
3. I could execute that command without trouble, try to go into the assets folder and that execute : `yarn install ` then `yarn build`

**Reply by benjaminjonard** [reply]
If it can help you, I managed to connect to a Mysql database like this : 

```
version: '3'

services:
    # Koillection
    koillection:
        image: koillection/koillection
        container_name: koillection
        restart: unless-stopped
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            - 81:80
        env_file:
            - .env
        volumes:
            - ./volumes/koillection/uploads:/
```

And in my .env.local
```
DB_DRIVER=pdo_mysql
DB_NAME=koillection
DB_HOST=127.0.0.1
DB_PORT=3306
DB_USER=root
DB_PASSWORD=password
DB_VERSION=8
```
