### ISSUE TITLE
Inventory detail page not available, error 500 instead

### ISSUE THREAD

**Issue by mcfisch** [benjaminjonard/koillection#423]
On my current install (docker-compose with beta image) the inventory function isn't working correctly. Creating an inventory is working it seems, as it appears in the "Inventories" list under "Tools" afterward. But trying to show its details/content does result in an error 500.

**Comment by benjaminjonard** [comment]
I can't reproduce this problem, could you provide me with logs of this error please  ?

You can find them in var/log/prod.log (using docker-compose:  `docker-compose exec koillection tail -f var/log/dev.log`)

**Comment by mcfisch** [comment]
I don't have a log, the directory is empty, and the other usual locations also don't have anything. However, I've enabled debugging in the `docker-compose.yml` and got this exception directly from Symphony as response when trying to open an inventory: 

>DivisionByZeroError
>---
>AbstractController->render()
>in `src/Controller/InventoryController.php` (line 90)`
>```
>        methods: ['GET']
>    )]
>    public function show(Inventory $inventory): Response
>    {
>        return $this->render('App/Inventory/show.html.twig', [
>            'inventory' => $inventory,
>        ]);
>    }
>}
>```

And here is the stack trace:
```
DivisionByZeroError:
Division by zero

  at var/cache/prod/twig/01/01ba95014da75b820184f6f3ae31ac42.php:234
  at __TwigTemplate_86706ee7ba41f06d38e2f33ed0ee10e8->macro_recursiveCollection()
     (vendor/twig/twig/src/Extension/CoreExtension.php:1202)
  at twig_call_macro()
     (var/cache/prod/twig/01/01ba95014da75b820184f6f3ae31ac42.php:250)
  at __TwigTemplate_86706ee7ba41f06d38e2f33ed0ee10e8->macro_recursiveCollection()
     (vendor/twig/twig/src/Extension/CoreExtension.php:1202)
  at twig_call_macro()
     (var/cache/prod/twig/01/01ba95014da75b820184f6f3ae31ac42.php:250)
  at __TwigTemplate_86706ee7ba41f06d38e2f33ed0ee10e8->macro_recursiveCollection()
     (vendor/twig/twig/src/Extension/CoreExtension.php:1202)
  at twig_call_macro()
     (var/cache/prod/twig/01/01ba95014da75b820184f6f3ae31ac42.php:155)
  at __TwigTemplate_86706ee7ba41f06d38e2f33ed0ee10e8->block_content()
     (vendor/twig/twig/src/Template.php:171)
  at Twig\Template->displayBlock()
     (var/cache/prod/twig/79/79c8219f1875a1824bd07e906e1b39b5.php:187)
  at __TwigTemplate_91bdb45b16f997f93ad7523639535468->block_body()
     (vendor/twig/twig/src/Template.php:171)
  at Twig\Template->displayBlock()
     (var/cache/prod/twig/54/548c4ff2ba2d14ccb2b911f0c05d0dc4.php:194)
  at __TwigTemplate_48f2b9641edc51e787c92b4f8d7e71f1->doDisplay()
     (vendor/twig/twig/src/Template.php:394)
  at Twig\Template->displayWithErrorHandling()
     (vendor/twig/twig/src/Template.php:367)
  at Twig\Template->display()
     (var/cache/prod/twig/79/79c8219f1875a1824bd07e906e1b39b5.php:50)
  at __TwigTemplate_91bdb45b16f997f93ad7523639535468->doDisplay()
     (vendor/twig/twig/src/Template.php:394)
  at Twig\Template->displayWithErrorHandling()
     (vendor/twig/twig/src/Template.php:367)
  at Twig\Template->display()
     (var/cache/prod/twig/01/01ba95014da75b820184f6f3ae31ac42.php:54)
  at __TwigTemplate_86706ee7ba41f06d38e2f33ed0ee10e8->doDisplay()
     (vendor/twig/twig/src/Template.php:394)
  at Twig\Template->displayWithErrorHandling()
     (vendor/twig/twig/src/Template.php:367)
  at Twig\Template->display()
     (vendor/twig/twig/src/Template.php:379)
  at Twig\Template->render()
     (vendor/twig/twig/src/TemplateWrapper.php:40)
  at Twig\TemplateWrapper->render()
     (vendor/twig/twig/src/Environment.php:277)
  at Twig\Environment->render()
     (vendor/symfony/framework-bundle/Controller/AbstractController.php:222)
  at Symfony\Bundle\FrameworkBundle\Controller\AbstractController->renderView()
     (vendor/symfony/framework-bundle/Controller/AbstractController.php:230)
  at Symfony\Bundle\FrameworkBundle\Controller\AbstractController->render()
     (src/Controller/InventoryController.php:90)
  at App\Controller\InventoryController->show()
     (vendor/symfony/http-kernel/HttpKernel.php:152)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw()
     (vendor/symfony/http-kernel/HttpKernel.php:74)
  at Symfony\Component\HttpKernel\HttpKernel->handle()
     (vendor/symfony/http-kernel/Kernel.php:202)
  at Symfony\Component\HttpKernel\Kernel->handle()
     (vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php:35)
  at Symfony\Component\Runtime\Runner\Symfony\HttpKernelRunner->run()
     (vendor/autoload_runtime.php:29)
  at require_once('/var/www/koillection/vendor/autoload_runtime.php')
     (public/index.php:5)
```

And here - for the sake of completeness - is my `docker-compose.yml`:
```
version: '3'

services:
    koillection-app:
        container_name: koillection-app
        image: koillection/koillection:beta
        restart: always
        ports:
            - 7070:80
        environment:
            - APP_ENV=prod
            - APP_DEBUG=1
            - DB_DRIVER=pdo_pgsql
            - DB_NAME=koillection
            - DB_HOST=koillection-postgresql
            - DB_PORT=5432
            - DB_USER=postgres
            - DB_PASSWORD=********************
            - DB_VERSION=14
            - PHP_TZ=America/Los_Angeles
            - HTTPS_ENABLED=0
        depends_on:
            - koillection-postgresql
        volumes:
            #- ./koillection-data/conf:/conf
            - ./koillection-data/uploads:/uploads

    koillection-postgresql:
        container_name: koillection-postgresql
        image: postgres:14
        environment:
            - POSTGRES_DB=koillection
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=********************
            - POSTGRES_HOST_AUTH_METHOD=trust
        ports:
            - 5432:5432
        volumes:
            - ./koillection-db:/var/lib/postgresql/data
```
