### ISSUE TITLE
Cannot Complete First Connection Setup

### ISSUE THREAD

**Issue by DebugDax** [benjaminjonard/koillection#431]
Hello,

After starting the container with a postgres database, I can visit the First Connection page but it won't let me past as it says 
`The value you selected is not a valid choice.`
https://i.imgur.com/kwNP7mF.png

for the Date Format field. This happens no matter what value I select, I've left it default and tried multiple values across 3 browsers.

My docker-compose
```
version: '3'

services:
    koillection:
        image: koillection/koillection
        container_name: koillection
        restart: unless-stopped
        ports:
            - 9013:80
        environment:
            - DB_DRIVER=pdo_pgsql
            - DB_NAME=koillection
            - DB_HOST=db
            - DB_PORT=5432
            - DB_USER=root
            - DB_PASSWORD=xxxx
            - DB_VERSION=12.2
            - PHP_TZ=America/New_York
            - HTTPS_ENABLED=0
        depends_on:
            - db
        volumes:
            - /home/dax/docker/data/koillection/conf:/conf
            - /home/dax/docker/data/koillection/uploads:/uploads

    db:
        image: postgres:latest
        container_name: db
        restart: unless-stopped
        ports:
            - 5432:5432
        environment:
            - POSTGRES_DB=koillection
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=xxxx
        volumes:
            - /home/dax/docker/data/postgresql:/var/lib/postgresql/data
```

Koillection Docker Log
```
**** Make sure the /conf and /uploads folders exist ****
**** Create the symbolic link for the /uploads folder ****
**** Copy the .env to /conf ****
**** Inject .env values ****
APP_DEBUG=0
APP_ENV=prod
DB_DRIVER=pdo_pgsql
DB_NAME=koillection
DB_HOST=db
DB_PORT=5432
DB_USER=root
DB_VERSION=12.2
DB_PASSWORD=xxxx
JWT_SECRET_KEY=%kernel.project_dir%/config/jwt/private.pem
JWT_PUBLIC_KEY=%kernel.project_dir%/config/jwt/public.pem
JWT_PASSPHRASE=xxxx
APP_SECRET=xxxx
**** Configure https ****
**** Migrate the database ****
[notice] Migrating up to App\Migrations\Postgresql\Version20220701151517
[notice] Migration App\Migrations\Mysql\Version20200429093452 skipped during Execution. Reason: "Migration can only be executed safely on 'mysql'."
[notice] Migration App\Migrations\Mysql\Version20200727114843 skipped during Execution. Reason: "Migration can only be executed safely on 'mysql'."
[notice] Migration App\Migrations\Mysql\Version20200812160901 skipped during Execution. Reason: "Migration can only be executed safely on 'mysql'."
[notice] Migration App\Migrations\Mysql\Version20200923193955 skipped during Execution. Reason: "Migration can only be executed safely on 'mysql'."
[notice] Migration App\Migrations\Mysql\Version20201010121132 skipped during Execution. Reason: "Migration can only be executed safely on 'mysql'."
[notice] Migration App\Migrations\Mysql\Version20201215214207 skipped during Execution. Reason: "Migration can only be executed safely on 'mysql'."
[notice] Migration App\Migrations\Mysql\Version20210127105342 skipped during Execution. Reason: "Migration can only be executed safely on 'mysql'."
[notice] Migration App\Migrations\Mysql\Version20210514100228 skipped during Execution. Reason: "Migration can only be executed safely on 'mysql'."
[notice] Migration App\Migrations\Mysql\Version20211207185256 skipped during Execution. Reason: "Migration can only be executed safely on 'mysql'."
[notice] Migration App\Migrations\Mysql\Version20220206133834 skipped during Execution. Reason: "Migration can only be executed safely on 'mysql'."
[notice] Migration App\Migrations\Mysql\Version20220206175335 skipped during Execution. Reason: "Migration can only be executed safely on 'mysql'."
[notice] Migration App\Migrations\Mysql\Version20220208094335 skipped during Execution. Reason: "Migration can only be executed safely on 'mysql'."
[notice] Migration App\Migrations\Mysql\Version20220630100634 skipped during Execution. Reason: "Migration can only be executed safely on 'mysql'."
[notice] Migration App\Migrations\Mysql\Version20220701175209 skipped during Execution. Reason: "Migration can only be executed safely on 'mysql'."
[notice] finished in 42.9ms, used 14M memory, 14 migrations executed, 0 sql queries

**** Create API keys ****
 [OK] Done! 
**** Create user and use PUID/PGID ****
 	User UID :	1000
 	User GID :	1000
**** Set Permissions ****
**** Create nginx log files ****
**** Setup complete, starting the server. ****
[14-Jul-2022 16:48:13] NOTICE: PHP message: PHP Warning:  Can't preload already declared class ReflectionEnum in /var/www/koillection/vendor/laminas/laminas-code/polyfill/ReflectionEnumPolyfill.php on line 8
```

Postgres Docker Log

```
PostgreSQL Database directory appears to contain a database; Skipping initialization
2022-07-14 16:48:08.077 UTC [1] LOG:  starting PostgreSQL 14.4 (Debian 14.4-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2022-07-14 16:48:08.077 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2022-07-14 16:48:08.077 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2022-07-14 16:48:08.080 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2022-07-14 16:48:08.084 UTC [26] LOG:  database system was shut down at 2022-07-14 16:45:14 UTC
2022-07-14 16:48:08.089 UTC [1] LOG:  database system is ready to accept connections      
```

Using version 1.3.5 on Debian Docker, via HTTP localhost.

There are no logs in var/logs/. (and setting APP_DEBUG=1 still does not make any)

It looks like it's trying to run Migrations for MySQL instead of Postgres which is causing the database to not be setup for first time use?
