### ISSUE TITLE
Can't add list to old items/collections

### ISSUE THREAD

**Issue by Izanagi52** [benjaminjonard/koillection#454]
Hello, thanks for the recent update, the list are really great !
But I have an error when I try to add a list to an item/collections created in 1.3.6, before the update.
The error occurs when I validate the change in the item/collections.
![IMG_20220728_111726](https://user-images.githubusercontent.com/21294450/181469772-1b621409-b313-41e2-bc15-7b772d7b7b13.jpg)

(It works perfectly with new item/collections)

**Comment by benjaminjonard** [comment]
Hello, could you try to activate debug mode and see if you have more details about this error ? (add APP_DEBUG=1 in your docker-compose file like below) 

```
koillection:
    image: koillection/koillection
    container_name: koillection
    restart: unless-stopped
    ports:
        - 80:80
    environment:
        - APP_DEBUG=1
        - DB_DRIVER=pdo_pgsql (or pdo_mysql)
        - DB_NAME=koillection
        - DB_HOST=db
        - DB_PORT=5432 (3306 for mysql)
        - DB_USER=root
        - DB_PASSWORD=root
        - DB_VERSION=12.2
        - PHP_TZ=Europe/Paris
        - HTTPS_ENABLED=1
```

Thanks
